# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-06 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgg', '0002_auto_20190206_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgg.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UGCCommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UGCLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='game',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gamecomment',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gamefollow',
            name='follow_game',
        ),
        migrations.RemoveField(
            model_name='gamefollow',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rategame',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ugc',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='ugc',
            name='like',
        ),
        migrations.RemoveField(
            model_name='ugc',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ugccomment',
            name='comments_like',
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='user_follow',
        ),
        migrations.AddField(
            model_name='ugc',
            name='like_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ugccomment',
            name='like_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ugccomment',
            name='ugc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bgg.UGC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rategame',
            name='game_rating',
            field=models.CharField(choices=[('select', '------'), ('love', 'LOVE'), ('like', 'LIKE'), ('dislike', 'DISLIKE'), ('hate', 'HATE')], default=None, max_length=10),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='GameComment',
        ),
        migrations.AddField(
            model_name='ugclike',
            name='ugc_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgg.UGC'),
        ),
        migrations.AddField(
            model_name='ugclike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ugccommentlike',
            name='ugc_comment_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgg.UGCComment'),
        ),
        migrations.AddField(
            model_name='ugccommentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
