# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-08 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0002_auto_20190208_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('name', 'year_published')]),
        ),
    ]
