# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-08 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0003_auto_20190208_1023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('name',)]),
        ),
    ]
