# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-06 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0003_auto_20190206_1125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFollow',
            new_name='FollowUser',
        ),
        migrations.RenameField(
            model_name='ugccommentlike',
            old_name='ugc_comment_like',
            new_name='ugc_comment',
        ),
        migrations.RenameField(
            model_name='ugclike',
            old_name='ugc_like',
            new_name='ugc',
        ),
        migrations.RemoveField(
            model_name='ugccomment',
            name='like_count',
        ),
        migrations.AddField(
            model_name='ugccommentlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ugclike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ugclike',
            name='like_type',
            field=models.CharField(choices=[('+1', 'LIKE'), ('-1', 'DISLIKE'), ('0', 'NEUTRAL')], default='0', max_length=10),
        ),
    ]
