# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-05 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0003_comment_follow_rategame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follow',
            field=models.BooleanField(choices=[(True, 'TRUE'), (False, 'FALSE')], default=False, max_length=10),
        ),
    ]
