# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-05 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0005_auto_20190205_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgg.Game'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamecomment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgg.Game'),
        ),
        migrations.AlterField(
            model_name='gamecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamefollow',
            name='follow_game',
            field=models.BooleanField(choices=[(True, 'TRUE'), (False, 'FALSE')], default=False),
        ),
        migrations.AlterField(
            model_name='gamefollow',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgg.Game'),
        ),
        migrations.AlterField(
            model_name='gamefollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rategame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgg.Game'),
        ),
        migrations.AlterField(
            model_name='rategame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ugccomment',
            name='comments_like',
            field=models.BooleanField(choices=[(True, 'TRUE'), (False, 'FALSE')], default=False),
        ),
        migrations.AlterField(
            model_name='ugccomment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgg.Game'),
        ),
        migrations.AlterField(
            model_name='ugccomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
