# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-11 11:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgg', '0005_auto_20190208_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('game_like', models.CharField(choices=[('like', 'LIKE'), ('dislike', 'DISLIKE')], default=None, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='likegame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgg.Game'),
        ),
        migrations.AddField(
            model_name='likegame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='likegame',
            unique_together=set([('user', 'game')]),
        ),
    ]
