# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-06 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgg', '0005_auto_20190206_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rategame',
            unique_together=set([('user', 'game')]),
        ),
    ]
