# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-05 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0006_auto_20190205_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecomment',
            name='game_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ugccomment',
            name='ugc_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
