# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-11 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0006_auto_20190211_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likegame',
            name='like_count',
        ),
        migrations.AddField(
            model_name='game',
            name='like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
