# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-12 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgg', '0007_auto_20190211_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGCReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ugc_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgg.UGCComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
