# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-13 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0008_ugcreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugcreport',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
