# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-13 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0009_auto_20190213_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugcreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
