# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-18 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0010_auto_20190213_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='note_to_admin',
        ),
        migrations.AddField(
            model_name='gameextend',
            name='note_to_admin',
            field=models.TextField(null=True),
        ),
    ]
