# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-20 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0011_auto_20190218_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ugcreport',
            name='ugc_comment',
        ),
        migrations.AddField(
            model_name='ugcreport',
            name='ugc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bgg.UGC'),
            preserve_default=False,
        ),
    ]
