# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-05 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0012_auto_20190220_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bgg.GameCategory'),
        ),
        migrations.AddField(
            model_name='gametag',
            name='game_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_name', to='bgg.Game'),
        ),
        migrations.AddField(
            model_name='gametag',
            name='tag_name',
            field=models.ManyToManyField(to='bgg.Tags'),
        ),
    ]
