# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-07 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0014_auto_20190306_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugc',
            name='game',
            field=models.ForeignKey(default=124, on_delete=django.db.models.deletion.CASCADE, to='bgg.Game'),
            preserve_default=False,
        ),
    ]
