# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-08 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0015_ugc_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ugccomment',
            old_name='ugc_comments',
            new_name='ugc_comment',
        ),
    ]
