# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0016_auto_20190308_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugccommentlike',
            name='game',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bgg.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ugccommentlike',
            name='ugc',
            field=models.ForeignKey(default=231, on_delete=django.db.models.deletion.CASCADE, to='bgg.UGC'),
            preserve_default=False,
        ),
    ]
