# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-12 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0017_auto_20190311_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='status',
            new_name='game_status',
        ),
    ]
