# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-13 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgg', '0018_auto_20190312_1308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('name', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='gametag',
            unique_together=set([('game_name', 'tag_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='ugc',
            unique_together=set([('user', 'game', 'ugc_title')]),
        ),
        migrations.AlterUniqueTogether(
            name='ugccommentlike',
            unique_together=set([('user', 'ugc_comment', 'game', 'ugc')]),
        ),
        migrations.AlterUniqueTogether(
            name='ugcreport',
            unique_together=set([('user', 'ugc')]),
        ),
    ]
