# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-19 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0019_auto_20190313_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.TextField(),
        ),
    ]
