# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-19 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg', '0020_auto_20190319_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
