# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-04 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuser',
            name='follow_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
