# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-27 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallogin',
            old_name='client_id',
            new_name='facebook_client_id',
        ),
        migrations.AddField(
            model_name='sociallogin',
            name='google_client_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
