# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-27 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190327_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallogin',
            old_name='id_token',
            new_name='google_id_token',
        ),
    ]
