# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190613_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
