# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-02 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190202_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='provinence',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
