# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-27 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190327_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=50),
        ),
    ]
