# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-04 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20190205_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('facebook', 'FACEBOOK'), ('google', 'GOOGLE')], default=None, max_length=10)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('client_id', models.CharField(max_length=250, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('id_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
