# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-05 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20190304_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallogin',
            old_name='expires_at',
            new_name='access_token_expiration_date',
        ),
        migrations.RemoveField(
            model_name='sociallogin',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sociallogin',
            name='last_name',
        ),
        migrations.AddField(
            model_name='sociallogin',
            name='family_name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='sociallogin',
            name='given_name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='sociallogin',
            name='google_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='sociallogin',
            name='name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='sociallogin',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
