# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-05 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20190305_0959'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sociallogin',
            unique_together=set([('provider', 'name')]),
        ),
    ]
