# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-05 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20190305_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallogin',
            name='google_id',
        ),
    ]
