# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-06 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0011_remove_sociallogin_google_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallogin',
            old_name='access_token',
            new_name='facebook_access_token',
        ),
        migrations.AddField(
            model_name='sociallogin',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sociallogin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sociallogin',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='sociallogin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sociallogin',
            name='provider',
        ),
    ]
