# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-08 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20190308_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallogin',
            old_name='refresh_token',
            new_name='facebook_refresh_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
        migrations.AddField(
            model_name='sociallogin',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
