# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-08 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20190308_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallogin',
            old_name='access_token_expiration_date',
            new_name='access_token_expiry',
        ),
    ]
