# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-15 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20190308_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='US', max_length=5),
            preserve_default=False,
        ),
    ]
