# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-19 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20190315_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(default='game title', max_length=5),
            preserve_default=False,
        ),
    ]
