# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-26 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20190319_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallogin',
            name='access_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
