# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-02 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag',
            new_name='tag_name',
        ),
        migrations.AddField(
            model_name='game',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Tags'),
        ),
    ]
