# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-29 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likegame',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
