# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-07 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='scan_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
