# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-20 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='gameextend',
            name='contained_in',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='gameextend',
            name='contains',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='gameextend',
            name='expands',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='gameextend',
            name='expansion',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='gameextend',
            name='family',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='gameextend',
            name='integrates_with',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='gameextend',
            name='note_to_admin',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='gameextend',
            name='reimplemented_by',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='gameextend',
            name='reimplements',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='gameextend',
            name='video_game_adaptation',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
