# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-07 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='gamecategory',
            unique_together=set([('category_name',)]),
        ),
    ]
