# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-26 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190320_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dislike_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
