# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-07 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190507_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ManyToManyField(to='game.GameCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(to='game.GameCategory'),
        ),
    ]
