# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-26 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_dislike_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dislike_count',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='like_count',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='views',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
