# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-17 07:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_auto_20190613_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='upload/')),
                ('videos', models.FileField(null=True, upload_to='upload/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_type', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.IntegerField(blank=True, null=True)),
                ('object_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='gamefeed',
            old_name='like_count',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='gamefeed',
            old_name='game_title',
            new_name='object_type',
        ),
        migrations.AddField(
            model_name='gamefeed',
            name='object_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RemoveField(
            model_name='gamefeed',
            name='game_comment',
        ),
        migrations.RemoveField(
            model_name='gamefeed',
            name='game_description',
        ),
        migrations.AlterUniqueTogether(
            name='gamefeed',
            unique_together=set([('user', 'game', 'object_type')]),
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('socialbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.SocialBase')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('game.socialbase',),
        ),
        migrations.AddField(
            model_name='socialbase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='likelog',
            unique_together=set([('object_type', 'object_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='gamecomment',
            unique_together=set([('users', 'game')]),
        ),
    ]
