# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190617_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='card_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='game',
            name='info_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='game',
            name='swipe_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterUniqueTogether(
            name='gamefeed',
            unique_together=set([]),
        ),
    ]
