# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-07 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190507_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydb',
            name='test',
        ),
        migrations.DeleteModel(
            name='MyDb',
        ),
    ]
