# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-20 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190507_1347'),
        ('game', '0002_auto_20190507_1344'),
    ]

    operations = [
    ]
