# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-28 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_auto_20190620_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('profilePic', models.CharField(blank=True, max_length=250, null=True)),
                ('replyCreatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('replyuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('commentCreatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('commentUserPicture', models.CharField(blank=True, max_length=250, null=True)),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('replyComments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.GameCommentReply')),
            ],
        ),
        migrations.RemoveField(
            model_name='gamefeeds',
            name='game_comment',
        ),
        migrations.AddField(
            model_name='gamefeeds',
            name='game_feed_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamefeeds',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.GameComments'),
        ),
    ]
