# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-20 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_merge_20190520_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='data',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='scan_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
