# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-30 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190520_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='status',
            field=models.CharField(choices=[('review', 'REVIEW'), ('published', 'PUBLISHED')], default='review', max_length=10),
        ),
    ]
