# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-27 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190520_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='game',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='mechanism',
        ),
        migrations.RemoveField(
            model_name='game',
            name='publisher',
        ),
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together=set([('publisher_name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='mechanism',
            unique_together=set([('mechanism',)]),
        ),
        migrations.AlterUniqueTogether(
            name='designer',
            unique_together=set([('designer_name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together=set([('artist_name',)]),
        ),
        migrations.AddField(
            model_name='game',
            name='artist',
            field=models.ManyToManyField(to='game.Artist'),
        ),
        migrations.AddField(
            model_name='game',
            name='designer',
            field=models.ManyToManyField(to='game.Designer'),
        ),
        migrations.AddField(
            model_name='game',
            name='mechanism',
            field=models.ManyToManyField(to='game.Mechanism'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.ManyToManyField(to='game.Publisher'),
        ),
    ]
