# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-12 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0009_auto_20190527_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=30)),
                ('game_comment', models.TextField(blank=True, null=True)),
                ('game_description', models.CharField(max_length=250)),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='status',
            field=models.CharField(choices=[('review', 'REVIEW'), ('published', 'PUBLISHED')], default='review', max_length=10),
        ),
        migrations.AddField(
            model_name='gamefeed',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.AddField(
            model_name='gamefeed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='gamefeed',
            unique_together=set([('user', 'game', 'game_title')]),
        ),
    ]
