# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-03 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_description'),
        ('game', '0009_gamecategory_status'),
    ]

    operations = [
    ]
