# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-10 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0012_auto_20190610_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFeedLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_type', models.CharField(choices=[('like', 'LIKE'), ('dislike', 'DISLIKE')], default='0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameFeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gamefeedlike',
            unique_together=set([('user', 'feed')]),
        ),
    ]
