# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-20 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ugccommentlike',
            old_name='ugc_comment',
            new_name='ugccomment',
        ),
        migrations.AlterUniqueTogether(
            name='ugccommentlike',
            unique_together=set([('user', 'ugccomment', 'game', 'ugc')]),
        ),
    ]
